metadata.format.version = "1.1"

[versions]

velocity = "3.4.0"
paper = "1.21.8-R0.1-SNAPSHOT"
minecraft = "1.21.10"

runtask = "3.0.2"
blossom = "2.2.0"
shadow = "9.3.1"
jmh = "0.7.3"
dokka = "2.1.0"

adventure = "4.26.1"
adventureModded = "6.8.0"
kotlin = "2.3.0"

fabric-api = "0.143.5+26.1"
fabric-loader = "0.18.4"

desertwell = "2.0.4"
bstats = "3.1.0"

[libraries]

velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
luckopermissionsapi = { group = "me.lucko", name = "fabric-permissions-api", version = "0.6.1" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-platform-fabric = { group = "net.kyori", name = "adventure-platform-fabric", version.ref = "adventureModded" }
adventure-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }

plugin-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
plugin-runtask = { module = "xyz.jpenilla.run-velocity:xyz.jpenilla.run-velocity.gradle.plugin", version.ref = "runtask" }

desertwell = { group = "net.william278", name = "DesertWell", version.ref = "desertwell" }

junit-bom = "org.junit:junit-bom:6.0.3"
jspecify = "org.jspecify:jspecify:1.0.0"

unnamedinject = "team.unnamed:inject:2.0.1"
brigadier = "com.mojang:brigadier:1.0.500"

bstats-core = { group = "org.bstats", name = "bstats-base", version.ref = "bstats" }
bstats-velocity = { group = "org.bstats", name = "bstats-velocity", version.ref = "bstats" }
bstats-sponge = { group = "org.bstats", name = "bstats-sponge", version.ref = "bstats" }
bstats-bukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

[plugins]

runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
